/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/Auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['RegisterRequest'];
          'text/json': components['schemas']['RegisterRequest'];
          'application/*+json': components['schemas']['RegisterRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['LoginRequest'];
          'text/json': components['schemas']['LoginRequest'];
          'application/*+json': components['schemas']['LoginRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Auth/confirm-email': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          email?: string;
          token?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Auth/forgot-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ForgotPasswordRequest'];
          'text/json': components['schemas']['ForgotPasswordRequest'];
          'application/*+json': components['schemas']['ForgotPasswordRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Auth/reset-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ResetPasswordRequest'];
          'text/json': components['schemas']['ResetPasswordRequest'];
          'application/*+json': components['schemas']['ResetPasswordRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Auth/refresh-token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['RefreshTokenRequest'];
          'text/json': components['schemas']['RefreshTokenRequest'];
          'application/*+json': components['schemas']['RefreshTokenRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Auth/change-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ChangePasswordRequest'];
          'text/json': components['schemas']['ChangePasswordRequest'];
          'application/*+json': components['schemas']['ChangePasswordRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ChangePasswordRequest: {
      oldPassword: string;
      newPassword: string;
    };
    Coin: {
      id?: string;
      symbol?: string;
      name?: string;
      image?: string;
      /** Format: double */
      currentPrice?: number | string;
      /** Format: double */
      priceChangePercentage24h?: number | string;
      /** Format: int64 */
      marketCap?: number | string;
      /** Format: int32 */
      marketCapRank?: number | string;
      description?: null | string;
      /** Format: date-time */
      lastUpdated?: string;
    };
    ForgotPasswordRequest: {
      email: string;
    };
    LoginRequest: {
      email: string;
      password: string;
    };
    MarketOverview: {
      /** Format: int32 */
      id?: number | string;
      /** Format: double */
      totalMarketCap?: number | string;
      /** Format: double */
      marketCapChange?: number | string;
      /** Format: double */
      totalVolume?: number | string;
      /** Format: double */
      volumeChange?: number | string;
      /** Format: double */
      btcDominance?: number | string;
      /** Format: double */
      btcPrice?: number | string;
      /** Format: double */
      ethPrice?: number | string;
      /** Format: date-time */
      timestamp?: null | string;
    };
    MarketStats: {
      coinId?: string;
      /** Format: double */
      currentPrice?: number | string;
      /** Format: int64 */
      marketCap?: number | string;
      /** Format: int32 */
      marketCapRank?: number | string;
      /** Format: double */
      totalVolume?: number | string;
      /** Format: double */
      high24h?: number | string;
      /** Format: double */
      low24h?: number | string;
      /** Format: double */
      circulatingSupply?: number | string;
      /** Format: double */
      totalSupply?: number | string;
      /** Format: double */
      maxSupply?: null | number | string;
      /** Format: double */
      priceChangePercentage24h?: number | string;
    };
    NewsArticle: {
      /** Format: int32 */
      id?: number | string;
      title?: string;
      content?: string;
      summary?: string;
      imageUrl?: string;
      source?: string;
      url?: string;
      isFeatured?: boolean;
      /** Format: date-time */
      publishedAt?: string;
    };
    OhlcvPoint: {
      /** Format: int64 */
      time?: number | string;
      /** Format: double */
      open?: number | string;
      /** Format: double */
      high?: number | string;
      /** Format: double */
      low?: number | string;
      /** Format: double */
      close?: number | string;
      /** Format: double */
      volume?: number | string;
    };
    PriceHistory: {
      /** Format: int32 */
      id?: number | string;
      coinId?: string;
      /** Format: double */
      price?: number | string;
      /** Format: date-time */
      timestamp?: string;
    };
    RefreshTokenRequest: {
      accessToken: string;
      refreshToken: string;
    };
    RegisterRequest: {
      username: string;
      email: string;
      password: string;
    };
    ResetPasswordRequest: {
      email: string;
      token: string;
      newPassword: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
