/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/Charts/{coinId}/ohlcv': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          period?: string;
        };
        header?: never;
        path: {
          coinId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['OhlcvPoint'][];
            'application/json': components['schemas']['OhlcvPoint'][];
            'text/json': components['schemas']['OhlcvPoint'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Coin: {
      id?: string;
      symbol?: string;
      name?: string;
      image?: string;
      /** Format: double */
      currentPrice?: number | string;
      /** Format: double */
      priceChangePercentage24h?: number | string;
      /** Format: int64 */
      marketCap?: number | string;
      /** Format: int32 */
      marketCapRank?: number | string;
      description?: null | string;
      /** Format: date-time */
      lastUpdated?: string;
    };
    MarketOverview: {
      /** Format: int32 */
      id?: number | string;
      /** Format: double */
      totalMarketCap?: number | string;
      /** Format: double */
      marketCapChange?: number | string;
      /** Format: double */
      totalVolume?: number | string;
      /** Format: double */
      volumeChange?: number | string;
      /** Format: double */
      btcDominance?: number | string;
      /** Format: double */
      btcPrice?: number | string;
      /** Format: double */
      ethPrice?: number | string;
      /** Format: date-time */
      timestamp?: null | string;
    };
    MarketStats: {
      coinId?: string;
      /** Format: double */
      currentPrice?: number | string;
      /** Format: int64 */
      marketCap?: number | string;
      /** Format: int32 */
      marketCapRank?: number | string;
      /** Format: double */
      totalVolume?: number | string;
      /** Format: double */
      high24h?: number | string;
      /** Format: double */
      low24h?: number | string;
      /** Format: double */
      circulatingSupply?: number | string;
      /** Format: double */
      totalSupply?: number | string;
      /** Format: double */
      maxSupply?: null | number | string;
      /** Format: double */
      priceChangePercentage24h?: number | string;
    };
    NewsArticle: {
      /** Format: int32 */
      id?: number | string;
      title?: string;
      content?: string;
      summary?: string;
      imageUrl?: string;
      source?: string;
      url?: string;
      isFeatured?: boolean;
      /** Format: date-time */
      publishedAt?: string;
    };
    OhlcvPoint: {
      /** Format: int64 */
      time?: number | string;
      /** Format: double */
      open?: number | string;
      /** Format: double */
      high?: number | string;
      /** Format: double */
      low?: number | string;
      /** Format: double */
      close?: number | string;
      /** Format: double */
      volume?: number | string;
    };
    PriceHistory: {
      /** Format: int32 */
      id?: number | string;
      coinId?: string;
      /** Format: double */
      price?: number | string;
      /** Format: date-time */
      timestamp?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
